
TCross1: [ 4.020,  -2.795] # 가운데 T
TCross2: [ 3.020, -7.295] # 오른쪽 맨 위 T
TCross3: [ 2.520, -7.295] # 오른쪽 2번째 T
TCross4: [ -0.450, -7.295] # 오른쪽 3번쨰 T
TCross5: [ -0.950, -7.295] # 오른쪽 제일 아래 T
TCross6: [ 3.020, 1.705]  # 왼쪽 맨 위 T
TCross7: [ 2.520, 1.705] # 왼쪽 2번째 T
LCross1: [ 3.020, -5.295] # 오른쪽 패널티 위 L
LCross2: [ -0.950, -5.295] # 오른쪽 패널티 아래 L
LCross3: [ 2.520, -6.295] # 오른쪽 골킥 위 L
LCross4: [ -0.450, -6.295] # 오른쪽 골킥 아래 L
LCross5: [ 4.020, -7.295] # 오른쪽 제일 끝 위 L
LCross6: [ -1.950, -7.295] # 오른쪽 제일 끝 아래 L
LCross7: [ 4.020, 1.705] # 왼쪽 제일 끝 위 L
LCross8: [ 3.020, -0.295] # 왼쪽 패널티 L
LCross9: [ 2.520, 0.705] # 왼쪽 골킥 L
XCross1: [ 1.780, -2.795] # 가운데 위 X
XCross2: [ 1.020, -2.795] # 중앙 X
XCross3: [ 0.270, -2.795] # 가운데 아래 X
XCross4: [ 1.020, 0.205] # 왼쪽 패널티 X
XCross5: [ 1.020, -5.5795] # 오른쪽 패널티 X


# 2차전 - T가 중앙이어야 함
XCross1: [ 1.780, -2.795] # 가운데 위 X
XCross2: [ 1.020, -2.795] # 중앙 X
XCross3: [ 0.270, -2.795] # 가운데 아래 X
XCross4: [ 1.020, 0.205] # 왼쪽 패널티 X
XCross5: [ 1.020, -5.5795] # 오른쪽 패널티 X

LCross1: [ 3.020, -5.295] # 오른쪽 패널티 위 L
LCross2: [ -0.950, -5.295] # 오른쪽 패널티 아래 L
LCross3: [ 2.520, -6.295] # 오른쪽 골킥 위 L
LCross4: [ -0.450, -6.295] # 오른쪽 골킥 아래 L
LCross5: [ 4.020, -7.295] # 오른쪽 제일 끝 위 L
LCross6: [ -1.950, -7.295] # 오른쪽 제일 끝 아래 L
LCross7: [ 4.020, 1.705] # 왼쪽 제일 끝 위 L
LCross8: [ 3.020, -0.295] # 왼쪽 패널티 L
LCross9: [ 2.520, 0.705] # 왼쪽 골킥 L
LCross10: []
LCross11: []
LCross12: []

TCross1: [ 4.020,  -2.795] # 가운데 T
TCross2: [ 3.020, -7.295] # 오른쪽 맨 위 T
TCross3: [ 2.520, -7.295] # 오른쪽 2번째 T
TCross4: [ -0.450, -7.295] # 오른쪽 3번쨰 T
TCross5: [ -0.950, -7.295] # 오른쪽 제일 아래 T
TCross6: [ 3.020, 1.705]  # 왼쪽 맨 위 T
TCross7: [ 2.520, 1.705] # 왼쪽 2번째 T
TCross8: []
TCross9: []
TCross10: []
